### PR TITLE
Binary testing branch & Makefile 

### PR DESCRIPTION
**Pull request by nabajour**
Some changes for binary testing: 
* storage class to dump stuff to HDF5
* binary comparison class 
* debug header file, to enable and disable dump to binary file and reload to compare to current values
* makefile fixes to read headers (and be able to configure g++ version)

### CODE REVIEW

**Comment by deitrr** [comment]
The merge went well... compile and run did not...
When I compile, I have warnings:
** 
src/output/esp_output.cu: In member function ‘void ESP::Output(int, double, double, double, double, double, double, double, double, char*, double)’:
src/output/esp_output.cu:168:34: warning: narrowing conversion of ‘(int)((ESP*)this)->ESP::point_num’ from ‘int’ to ‘double’ inside { } [-Wnarrowing]
         double point_num_a[] = {point_num};
                                  ^
src/output/esp_output.cu:186:20: warning: narrowing conversion of ‘(int)((ESP*)this)->ESP::nv’ from ‘int’ to ‘double’ inside { } [-Wnarrowing]
         double nv_a[] = {nv};
                    ^ 
**

And when I try to run it, I get this:
**bin/esp: error while loading shared libraries: libhdf5_cpp.so.101: cannot open shared object file: No such file or directory**

Am I missing a dependence?

**Comment by nabajour** [comment]
Ah, yes, that's the HDF5 C++ library that's missing. I tried using the C++ header and library instead of the C lib.

Surprised that it didn't complain on the header file.
Should be in libhdf5-dev package.

**Comment by deitrr** [comment]
Argh, so I tried "sudo apt-get install libhdf5-serial-dev" and "sudo apt-get install libhdf5-dev" which installed without issue. But I still get the same error when I try to run bin/esp. Any ideas?

**Comment by deitrr** [comment]
I think h5py might be interfering with the library linkage. The output from make is:
h5libs="-lhdf5_hl_cpp -lhdf5_cpp -lhdf5_hl -lhdf5 "
h5libdir="-L/home/deitrick/anaconda3/lib -L/home/deitrick/anaconda3/lib "
h5include="-I/home/deitrick/anaconda3/include "

**Comment by nabajour** [comment]
ah, weird. 
Check the output of h5++:
`% h5c++ -show -shlib`
and what h5c++ it uses:
`% which h5c++`
You can also find what library the dynamic loader sees as dependencies with ldd
`% ldd bin/esp`
mine shows:

    % ldd bin/esp                              
                    
        linux-vdso.so.1 (0x00007ffd4458e000)
        libhdf5_hl_cpp.so.100 => /usr/lib/x86_64-linux-gnu/libhdf5_hl_cpp.so.100 (0x00007fa572ac5000)
        libhdf5_cpp.so.100 => /usr/lib/x86_64-linux-gnu/libhdf5_cpp.so.100 (0x00007fa57285d000)
        libhdf5_serial_hl.so.100 => /usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.so.100 (0x00007fa572639000)
        libhdf5_serial.so.100 => /usr/lib/x86_64-linux-gnu/libhdf5_serial.so.100 (0x00007fa5720d0000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa571ec8000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa571caa000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa571aa6000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa571725000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa571392000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa57117a000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa570dc0000)
        libsz.so.2 => /usr/lib/x86_64-linux-gnu/libsz.so.2 (0x00007fa570bbd000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa57099f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa573172000)
        libaec.so.0 => /usr/lib/x86_64-linux-gnu/libaec.so.0 (0x00007fa570797000)

**Comment by deitrr** [comment]
Hmm...

I think that I take back what I said before. The missing library file exists in anaconda3/lib:
```
deitrick@thule:~/Research/fork_thor/THOR$ ls /home/deitrick/anaconda3/lib/libhdf5_cpp.*
/home/deitrick/anaconda3/lib/libhdf5_cpp.a
/home/deitrick/anaconda3/lib/libhdf5_cpp.la
/home/deitrick/anaconda3/lib/libhdf5_cpp.so
/home/deitrick/anaconda3/lib/libhdf5_cpp.so.101
/home/deitrick/anaconda3/lib/libhdf5_cpp.so.101.0.0
```
```
deitrick@thule:~/Research/fork_thor/THOR$ which h5c++
/home/deitrick/anaconda3/bin/h5c++
```

Still, it cannot find libhdf5_cpp.so.101 (and it is linked to a different library, somehow):
```
deitrick@thule:~/Research/fork_thor/THOR$ ldd bin/esp
	linux-vdso.so.1 =>  (0x00007ffcd8bf2000)
	libhdf5_cpp.so.101 => not found
	libhdf5.so.101 => /usr/local/hdf5/lib/libhdf5.so.101 (0x00007f93dd868000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f93dd660000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f93dd443000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f93dd23f000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f93dcebd000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f93dcbb4000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f93dc99e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f93dc5d4000)
	libz.so.1 => /usr/local/lib/libz.so.1 (0x00007f93dc3b8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f93dde33000)
```

**Comment by nabajour** [comment]
What does 
    % ldd bin/esp 
say?

Try something like this:
    % export LD_LIBRARY_PATH="/home/deitrick/anaconda3/lib/:$LD_LIBRARY_PATH"
    % bin/esp

If it works, it means that this library is not on the path for the dynamic library loader.

**Comment by deitrr** [comment]
Sorry, I think I updated my comment after you'd already seen it. See the edited comment above. 
The export command above does not resolve the issue, I think because it is not actually linking to the anaconda3 library.

**Comment by nabajour** [comment]
try
    % sudo ldconfig -v
maybe it needs to rebuild the cache of path to libraries and didn't do it since the install?

**Comment by deitrr** [comment]
Alas, no luck:
```
deitrick@thule:~/Research/fork_thor/THOR$ ldd bin/esp
	linux-vdso.so.1 =>  (0x00007ffe2f9b7000)
	libhdf5_cpp.so.101 => not found
	libhdf5.so.101 => /usr/local/hdf5/lib/libhdf5.so.101 (0x00007f34880bf000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3487eb7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3487c9a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3487a96000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3487714000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f348740b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f34871f5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3486e2b000)
	libz.so.1 => /usr/local/lib/libz.so.1 (0x00007f3486c0f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f348868a000)
deitrick@thule:~/Research/fork_thor/THOR$ bin/esp
bin/esp: error while loading shared libraries: libhdf5_cpp.so.101: cannot open shared object file: No such file or directory
```
Do you have any idea why it is linking the /usr/local/hdf5/ library, instead of /home/deitrick/anaconda3/, which it says it is using?

**Comment by nabajour** [comment]
Actually, it seems like the make file finds the configuration executable h5c++ in /home/deitrick/anaconda3/, and uses that for compilation (finding header files and stuff).
The dynamic linker, at run time, finds hdf5 library  for C in /usr/local/hdf5/lib

The version from the package manager on an ubuntu machine should be somewhere in
/usr/lib/x86_64-linux-gnu/hdf5/serial/
or
/usr/lib/x86_64-linux-gnu/

It seems to find your hdf5 library in /usr/local. Did you at some point compile it and install it by hand ? and didn't compile the C++ stuff?

**Comment by deitrr** [comment]
That does ring a bell. Can I override this or uninstall old versions?

**Comment by nabajour** [comment]
Not sure how it was installed, dunno if it provides an uninstall tool. Maybe start by moving or renaming the /usr/local/hdf5 folder to get it out of the way?

**Comment by deitrr** [comment]
Aha! Progress. I moved /usr/local/hdf5, then I had to update the path again with: export LD_LIBRARY_PATH="/home/deitrick/anaconda3/lib/:$LD_LIBRARY_PATH". Now is working.

**Comment by nabajour** [comment]
Great! It works with the anaconda3 lib. Still not using the ones from the system, but that's not to much of an issue.

What does ldd say? Pointing to anaconda?

**Comment by deitrr** [comment]
Yes! 

Is there a nice way to circumvent this kind of issue with make? Or spit out some warnings that make it easier to diagnose?

**Comment by nabajour** [comment]
Here we have 3 different installs on one machine (package manager, anaconda and local install), not sure we can have a simple solution to circumvent all types of weird state people can get their system into. 

But we can try to print out the path to h5c++. Maybe we can also print out the path of the libraries found by ldd, to provide some hints to the user to help him understand what's happening. 
I can also check if CMake can give more diagnosis.

**Comment by deitrr** [comment]
Thanks!

**Pull request merged**
